export default [
  { email: 'yonia@scytale.ai',       role: 'admin', regions: [] },
  { email: 'karlm@scytale.ai',       role: 'admin', regions: [] },
  { email: 'simonn@scytale.ai',      role: 'sdr',   regions: ['aus', 'nordics', 'taiwan'] },
  { email: 'darrent@scytale.ai',     role: 'sdr',   regions: ['aus', 'nordics', 'taiwan'] },
  { email: 'katiem@scytale.ai',      role: 'sdr',   regions: ['aus', 'benelux', 'taiwan'] },
  { email: 'jamesb@scytale.ai',      role: 'sdr',   regions: ['benelux', 'uk'] },
  { email: 'chumam@scytale.ai',      role: 'sdr',   regions: ['benelux', 'dach'] },
  { email: 'tylorvw@scytale.ai',     role: 'sdr',   regions: ['benelux', 'uk'] },
  { email: 'ryane@scytale.ai',       role: 'sdr',   regions: ['benelux', 'uk'] },
  { email: 'khadym@scytale.ai',      role: 'sdr',   regions: ['benelux', 'uk'] },
  { email: 'jillianl@scytale.ai',    role: 'sdr',   regions: ['dach', 'nordics'] },
  { email: 'davidv@scytale.ai',      role: 'sdr',   regions: ['dach', 'uk'] },
  { email: 'darrenm@scytale.ai',     role: 'sdr',   regions: ['dach'] },
  { email: 'lusandam@scytale.ai',    role: 'sdr',   regions: ['uk'] },
  { email: 'kristophers@scytale.ai', role: 'sdr',   regions: ['uk'] },
  { email: 'aleksandra@scytale.ai',  role: 'sdr',   regions: ['poland', 'uk'] },
  { email: 'severop@scytale.ai',     role: 'sdr',   regions: ['dach', 'nordics'] },
  { email: 'veronicat@scytale.ai',   role: 'sdr',   regions: ['aus', 'benelux', 'taiwan'] },
  { email: 'danielp@scytale.ai',     role: 'sdr',   regions: ['dach'] },
  { email: 'millicentd@scytale.ai',  role: 'inbound', regions: [] },
  { email: 'ivonne@scytale.ai',      role: 'inbound', regions: [] },
  { email: 'sandilen@scytale.ai',    role: 'sdr',   regions: ['uk', 'aus'] },
];
