module.exports = [
  { email: 'yonia@scytale.ai',       role: 'admin', regions: [] },
  { email: 'simamkelen@scytale.ai',  role: 'sdr',   regions: ['aus', 'nordics'] },
  { email: 'darrent@scytale.ai',     role: 'sdr',   regions: ['aus', 'nordics'] },
  { email: 'katiem@scytale.ai',      role: 'sdr',   regions: ['aus', 'benelux'] },
  { email: 'jamesb@scytale.ai',      role: 'sdr',   regions: ['benelux', 'uk'] },
  { email: 'chumam@scytale.ai',      role: 'sdr',   regions: ['benelux', 'dach'] },
  { email: 'tylorvw@scytale.ai',     role: 'sdr',   regions: ['benelux', 'uk'] },
  { email: 'ryane@scytale.ai',       role: 'sdr',   regions: ['benelux', 'uk'] },
  { email: 'khadym@scytale.ai',      role: 'sdr',   regions: ['benelux', 'uk'] },
  { email: 'jillianl@scytale.ai',    role: 'sdr',   regions: ['dach', 'nordics'] },
  { email: 'davidv@scytale.ai',      role: 'sdr',   regions: ['dach', 'uk'] },
  { email: 'darrenm@scytale.ai',     role: 'sdr',   regions: ['dach'] },
  { email: 'lusandam@scytale.ai',    role: 'sdr',   regions: ['uk'] },
  { email: 'kristophers@scytale.ai', role: 'sdr',   regions: ['uk'] },
];
